name: Test action

on:
  schedule:
    - cron: '50 22 * * *'  # 23:50 CET (22:50 UTC)
  workflow_dispatch:  # Optional: Allow manual triggers

jobs:
  sync-characters:
    runs-on: ubuntu-latest
    steps:
    - name: Sync characters with retries
      env:
        ENDPOINT_URL: https://flexyserver.vercel.app/characters

      run: |
        MAX_RETRIES=3
        RETRY_DELAY=10
        attempt=1
        
        while [ $attempt -le $MAX_RETRIES ]; do
          echo "Attempt $attempt of $MAX_RETRIES"
          
          response=$(curl -si -X GET \
            -H "Content-Type: application/json" \
            -H "x-api-key: $API_KEY" \
            "$ENDPOINT_URL" \
            -o response.body \
            -w "%{http_code}")

          status_code=${response: -3}

          if [ $status_code -ge 200 ] && [ $status_code -lt 300 ]; then
            echo "Sync successful! Status code: $status_code"
            exit 0
          else
            echo "Sync failed! Status code: $status_code"
            if [ $attempt -lt $MAX_RETRIES ]; then
              echo "Retrying in $RETRY_DELAY seconds..."
              sleep $RETRY_DELAY
            fi
          fi
          attempt=$((attempt + 1))
        done
        exit 1